command_timeout = 100

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$buf\
$nix_shell\
$memory_usage\
$env_var\
$mise\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[username]
show_always = true
format = '[$user]($style)[]()'
style_user = 'bold green'

[hostname]
ssh_only = false
ssh_symbol = '[\[R\]](white)'
format = '[@$hostname$ssh_symbol]($style):'
style = 'bold green'

[directory]
truncation_length = 99

[memory_usage]
#disabled = false

[time]
disabled = false

[status]
disabled = false
symbol = "[x](bold red) "
